spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/blog_app_db

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER_ADDRESS}
    properties:
      mail:
        debug: true
        smtp:
          ssl:
            protocols:
              TLSv1.2
          auth: true
          starttls:
            enable: true
    password: ${MAIL_SENDER_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

    show-sql: true

jwt:
  private.key: classpath:private.key
  public.key: classpath:public.key